[package]
name = "embedded-wasm-nrf52"
version = "0.1.0"
edition = "2021"

[features]
default = ["nrf52840-pac/rt"]


[dependencies]
cortex-m = "0.7.3"
cortex-m-rt = "0.7.0"
nrf52840-pac = "0.10.0"
nrf-hal-common = { version = "0.14.0", default-features=false, features=[ "52840" ] }

embedded-hal = "1.0.0-alpha.5"

wasm-embedded-spec = { version="*", default_features=false }
wasm-embedded-rt-wasm3 = { version="*", default-features=false }
defmt = "0.3.1"


[patch.crates-io]
wasm-embedded-spec = { path = "../wasm/spec" }
wasm-embedded-rt-wasm3 = { path = "../wasm/rt_wasm3" }

