# cargo-embed configuration
# via: https://github.com/probe-rs/cargo-embed/blob/master/src/config/default.toml

[default.general]
chip="NRF52840"

[default.rtt]
enabled = true
channels = [
    { up = 0, name = "defmt_name", format = "Defmt" }
]
